### ISSUE TITLE
[vuejs] error with Hivemind wiki

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-runtime#68] opened 2016-12-22 03:51 UTC
I just pull the newest code to try new VueJs features.

When open a wikispace using VueJS, error occurs:
- Url: `http://localhost:8080/vapps/hm/wiki/DEMO`
- Error Message: `Cannot get wiki page info without wikiSpaceId parameter or URL path element`

It's still ok with normal screen (http://localhost:8080/apps/hm/wiki/DEMO)

**Comment by jonesde** [comment] 2016-12-26 20:17
Thank you for trying out this stuff. It is all still very new and only in the last couple days has the majority of functionality in existing screens been working. When you filed this issue there were a few things that still needed to be handled in the webroot Vue component and related functionality (in WebrootVue.js), and this error was just one of them (caused by support for extra path elements beyond the screen name not being supported by the router). That is now fixed as is the client side tree rendering and multiple type support under render-mode.

As of now wiki.xml and other functionality in the HiveMind task manager app (and admin app) seems to be working well and issues in general should be isolated (as opposed to 5 days ago when screens like HM wiki.xml weren't even close). If you find other issues thank you in advance for filing them.

**Closed by jonesde** 2016-12-26 20:17 UTC
