### ISSUE TITLE
Issue with decimal number and locale de

### ISSUE THREAD

**Issue by okroener** [moqui/moqui-runtime#122] opened 2018-01-12 18:09 UTC
I have defined a field 

type="number-decimal" not-null="false"

With a user and local="en" this works correctly: 1.23 get 1.23 ... and so on ...

When I change the locale to "de" ... and put in 1**,**23 geht an error:

![moquierrornumber](https://user-images.githubusercontent.com/4545439/34889008-c1137f1c-f7cc-11e7-9a3e-f42b296eed94.PNG)

When I enter 1.23, it becomes 123 witout decimal places ...

I am using Moqui 2.1.1RC ...

What am I doing wrong?

**Comment by jonesde** [comment] 2018-01-12 21:45
Going forward please file requests for support on the new HiveMind instance on moqui.org. For more information about community infrastructure see:

https://www.moqui.org/docs/moqui/Community+Guide

In the near future issues on GitHub will be disabled altogether.

This issue is a duplicate of issue #49 on moqui-framework, and related to pull request #93 on moqui-runtime:

https://github.com/moqui/moqui-framework/issues/49
https://github.com/moqui/moqui-runtime/pull/93

**Closed by jonesde** 2018-01-12 21:45 UTC

**Comment by okroener** [comment] 2018-01-13 10:36
Many thanks, I have signed up with HiveMind and will post further request there, Thx
