### ISSUE TITLE
Incorrect URL of menuData transition in webroot.xml (application running in dynamic mode on a server with multiple jetty containers)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#111] opened 2017-11-19 12:22 UTC
Transition menuData in webroot.xml does not work when application runs in dynamic mode. The request that is made to fetch items of the menu is forwarded to an incorrect URL.

Application is running on URL [server]/[application], but the URL (of menuData transition) is constructed as [server]/menuData/[application]/apps. There are multiple instances of jetty running on the server, with httpd running as reverse proxy.

![image](https://user-images.githubusercontent.com/14863763/32990571-03aa2c66-cd2c-11e7-991f-bdb1c0af8649.png)

And the result is:

![image](https://user-images.githubusercontent.com/14863763/32990582-3164337c-cd2c-11e7-9ef2-f6f8abf5e90a.png)

![image](https://user-images.githubusercontent.com/14863763/32990604-865df3a4-cd2c-11e7-972f-89784c4a84f0.png)

**Comment by mrovnanik** [comment] 2017-11-19 13:59
When diving into the topic, it seems that the WebRootVue.js is calling the transition using incorrect URL.

**Comment by mrovnanik** [comment] 2017-11-19 14:22
![image](https://user-images.githubusercontent.com/14863763/32991518-6c2518d0-cd3d-11e7-8b9c-44250cdd03a5.png)

**Comment by jonesde** [comment] 2017-11-19 18:00
Trying to figure out how you have this setup and how I would reproduce it... in general I don't care about theories about what is wrong, it is far more important to have:

1. steps to reproduce (ie what you did in terms of configuration, code if relevant, user/other system interaction)
2. what happened (how it is behaving)
3. how that is different from how you expect/need it to behave

It sounds like in this case you have:

1. request a URL like /hotels.../vapps
1.a. a reverse proxy is setup that is forwarding to a Jetty server based on a path (/hotels...)
1.b. within the Jetty server the moqui webapp is mounted on ROOT
2. the vapps screen loaded, loading the WebrootVue SPA shell, but the request for menuData returned a 404 by the reverse proxy because the URL generated was /menuData/hotels.../apps and /menuData is not a valid path that the reverse proxy knows about
3. the path for the the menuData request should have "/hotels..." before /menuData instead of after it

Reproducing that setup is a bit of a pain, one thing I'm wondering about your setup is what HttpServletRequest.getServletPath() returns... does it return "hotels..." the same as if the webapp was mounted in the servlet container on a path other than ROOT?

The vapps stuff (and the WebrootVue SPA shell) was not written for either scenario (webapp mounted within Jetty on a path other than ROOT, and Jetty or other servlet container itself mounted through a reverse proxy on a path other than ROOT, and technically you could have both). If HttpServletRequest.getServletPath() returns the desired path this is a lot easier, otherwise we need a configuration option for a prefix path for the servlet container itself and that needs to be used in addition to the servlet context path within the servlet container.

This could be done, but I suspect there will be many issues other than just how the menuData path is built. Did you by chance test the non-dynamic UI under the /apps path?

**Comment by mrovnanik** [comment] 2017-11-19 18:46
Starting from the end, yes. I switched the default subscreen in webroot.xml from vapps to apps and it works.

`ec.web.getRequest()` returns 
> Request(GET https://[SERVER]/hotelslovan-ekonomika/apps/AppList)

`ec.web.getRequest().getServletPath()` returns NULL

**Comment by mrovnanik** [comment] 2017-11-19 19:40
![image](https://user-images.githubusercontent.com/14863763/32994582-cf8be4c2-cd69-11e7-994f-fb3def62d6e6.png)

**Comment by jonesde** [comment] 2017-11-19 20:47
What does the WebFacadeStub have to do with this, ie why did you include that screen image?

If ec.web.request.getServletPath() returns null this is a bigger issue, and it means one of the steps to reproduce is to setup a reverse proxy that forwards requests based on a path (as opposed to the more simple setup of mounting the webapp within the servlet container on a path other than ROOT, though there is likely an issue with that too).

FYI, there is little chance I'll get to this soon as much as I'd like to make sure both of these scenarios are well supported. There are too many other open issues right now and most of my very limited weekly time budget for going through these is spent on low-quality issue reports and "contributions" (so many pull requests are along the lines of make it work for my scenario, I don't care if it breaks other things).

**Comment by mrovnanik** [comment] 2017-11-19 21:08
Sorry for confusing.

This is part of the httpd conf:
![image](https://user-images.githubusercontent.com/14863763/32995507-ca329082-cd75-11e7-9242-f5910d29cc4d.png)

I got your point with the solution. I need to dive into the issue. Hope I figure out a workaround in a reasonable time. 

Thanks anyway David. For the hints.

**Comment by jonesde** [comment] 2017-11-20 01:53
FWIW I put a bit of time into testing this using a servlet context path that is not empty and made a number of changes, now in moqui-framework, moqui-runtime, and SimpleScreens. This is still experimental at best but the basics work.

It still uses ServletContext.getContextPath() (usually returns the same as request.getContextPath()). BTW I mentioned the wrong method name earlier, should have asked you to see what request.getContextPath() returns, not what request.getServletPath() returns. Based on your httpd conf settings it looks like you're forwarding with the path so that should work fine. 

If not the next step to support your case would be to add a configuration option to set a base path even before the servlet context (webapp) path. That would be something entirely new for Moqui, but it is something I've considered before and I know some other web applications support (Kibana for example, which we reverse proxy through a Jetty proxy servlet, see the MoquiConf.xml file in the moqui-elasticsearch component for an example).

More testing is needed, but the basic navigation and form submits and such seem to work fine. There are some menu image URLs that I noticed aren't getting cleaned up correctly, and probably some other issues, but at least the basics are there now. There was partial support for this before, at least the servlet context path is known by WebrootVue.js, but it wasn't really using it at all, and there were various places where it needed to.

If you don't mind I'll reopen this issue and hope to get more feedback from you.

**Comment by mrovnanik** [comment] 2017-11-20 09:11
OK. Of course, I shall give feedback. Thanks many times David.

**Comment by jonesde** [comment] 2017-12-13 06:24
Any updates on this? If not I'll close the issue.

**Comment by mrovnanik** [comment] 2017-12-13 07:58
Yes, it works. Except for the menu images. Some of them are not generated properly.

**Comment by jonesde** [comment] 2017-12-25 17:25
Which menu images? If there are any that use a plain URL (or path) instead of a 'transition' or screen path for the URL then they will fail as the framework does not try to generate the full path or full URL.

**Comment by jonesde** [comment] 2018-01-17 18:05
Closing as part of general cleanup for the move to HiveMind and for no recent activity on this issue. If this comes up again or anyone wants to pursue it feel free to create a request on moqui.org. For more information see:

https://www.moqui.org/m/docs/moqui/Community+Guide

**Closed by jonesde** 2018-01-17 18:05 UTC
